import { SERVICE_PAGES } from "../src/data/service-pages.ts";
import { PRICES } from "../src/data/prices.ts";

const slugs = new Set<string>();
for (const p of SERVICE_PAGES) slugs.add(p.slug);

const priceUnits: Record<string,string> = {};
for (const it of PRICES) priceUnits[it.id] = it.unit ?? "fixed";

const out = `// AUTO-GENERATED by scripts/gen-edge-allowlists.ts — do not edit.
// Source: src/data/service-pages.ts (${slugs.size} slugs), src/data/prices.ts (${PRICES.length} items).
export const SERVICE_SLUG_ALLOWLIST: ReadonlySet<string> = new Set(${JSON.stringify([...slugs].sort())});
export const CALCULATOR_MODE_ALLOWLIST: ReadonlySet<string> = new Set(["repair","house","construction","engineering"]);
export const PRICE_ID_UNITS: Readonly<Record<string,string>> = ${JSON.stringify(priceUnits)};
export const PRICE_VERSION_ALLOWED = "2026-06";
export const TOTAL_SERVICE_SLUGS = ${slugs.size};
export const TOTAL_PRICE_ITEMS = ${PRICES.length};
`;
await Bun.write("supabase/functions/_shared/allowlists.ts", out);
console.log("slugs:", slugs.size, "prices:", PRICES.length);