import { createClient } from '@supabase/supabase-js';
import { mkdirSync, readdirSync, readFileSync, writeFileSync, existsSync, statSync, cpSync } from 'fs';
import { resolve, join, relative } from 'path';
import { execSync } from 'child_process';
import { PRICES } from '../../src/data/prices.ts';
import { SERVICE_PAGES } from '../../src/data/service-pages.ts';
import { getOperatorStatus, isPublicAuthEnabled, isPublicDataCollectionEnabled } from '../../src/lib/operator-configuration.ts';
const root=process.cwd(), out=resolve(root,'.audit/stage-3C'); mkdirSync(out,{recursive:true});
const readJson=(p:string)=>JSON.parse(readFileSync(resolve(out,p),'utf8'));
const write=(p:string,v:any)=>writeFileSync(resolve(out,p), typeof v==='string'?v:JSON.stringify(v,null,2));
const URL=process.env.SUPABASE_URL!, SR=process.env.SUPABASE_SERVICE_ROLE_KEY!;
const admin=createClient(URL,SR,{auth:{persistSession:false,autoRefreshToken:false}});
const migrationsDir=resolve(out,'migrations'); mkdirSync(migrationsDir,{recursive:true});
for(const f of readdirSync(resolve(root,'supabase/migrations')).filter(f=>f.endsWith('.sql'))) cpSync(resolve(root,'supabase/migrations',f),resolve(migrationsDir,f));
for (const [name,cmd] of Object.entries({
 'database-live-schema.json': "psql -Atc \"select json_agg(row_to_json(t)) from (select table_schema,table_name,column_name,data_type,is_nullable from information_schema.columns where table_schema in ('public','storage') order by 1,2,ordinal_position)t\"",
 'rls-live-policies.json': "psql -Atc \"select coalesce(json_agg(row_to_json(t)),'[]'::json) from (select schemaname,tablename,policyname,permissive,roles,cmd,qual,with_check from pg_policies where schemaname in ('public','storage') order by 1,2,3)t\"",
 'database-live-functions.json': "psql -Atc \"select coalesce(json_agg(row_to_json(t)),'[]'::json) from (select n.nspname schema,p.proname name,pg_get_function_identity_arguments(p.oid) args,p.prosecdef security_definer,p.proconfig config from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' order by 1,2)t\"",
 'database-live-grants.json': "psql -Atc \"select coalesce(json_agg(row_to_json(t)),'[]'::json) from (select grantee,table_schema,table_name,privilege_type from information_schema.role_table_grants where table_schema='public' order by 1,2,3,4)t\"",
})) { try { const s=execSync(cmd,{cwd:root,encoding:'utf8'}).trim(); write(name, s?JSON.parse(s):[]); } catch(e:any){ write(name,{error:e.message}); } }
const func = await admin.rpc('cleanup_expired_rate_limits');
const functionRows:any[] = JSON.parse(readFileSync(resolve(out,'database-live-functions.json'),'utf8'));
const testOnlyRpcExists = functionRows.some((f:any)=>f.name==='stage3c_fault_injection_submission');
const remainingRows = await admin.from('estimate_requests').select('id',{count:'exact',head:true}).like('source_path','/stage3c%');
const remainingStorage = await admin.storage.from('project-documents').list('',{limit:100,search:'stage3c'});
const edge=readJson('edge-integration-matrix.json'), idem=readJson('concurrent-idempotency-test.json'), rl=readJson('rate-limit-parallel-test.json'), rb=readJson('transaction-rollback-test.json'), cleanup=readJson('rate-limit-cleanup-test.json'), cors=readJson('cors-integration-test.json'), trusted=readJson('trusted-client-address-test.json'), missing=readJson('missing-salt-test.json'), storage=readJson('storage-integration-test.json'), rls=readJson('rls-test-matrix.json'), profile=readJson('profile-permissions-test.json'), secdef=readJson('security-definer-test.json'), td=existsSync(resolve(out,'test-data-cleanup.json'))?readJson('test-data-cleanup.json'):{};
const operator=getOperatorStatus();
const totals={priceItems:PRICES.length,servicePages:SERVICE_PAGES.length,repairServicePages:SERVICE_PAGES.filter((p:any)=>p.category==='repair'&&!p.isStub).length,constructionServicePages:SERVICE_PAGES.filter((p:any)=>p.category==='construction'&&!p.isStub).length,engineeringServicePages:SERVICE_PAGES.filter((p:any)=>p.category==='engineering'&&!p.isStub).length,calculatorRoutes:1,calculatorModes:4,clientRoutesActivated:0,adminRoutesActivated:0};
const flags:any={positiveEdgeHttpTestsExecuted:edge.executed&&edge.passed,validAnonymousSubmissionPassed:edge.results?.find((r:any)=>r.name==='validAnonymousSubmission')?.passed===true,validAuthenticatedSubmissionPassed:edge.results?.find((r:any)=>r.name==='validAuthenticatedSubmission')?.passed===true,concurrentIdempotencyPassed:idem.executed&&idem.passed,parallelRateLimitPassed:rl.executed&&rl.passed,consentRollbackPassed:rb.executed&&rb.passed,rateLimitCleanupPassed:cleanup.executed&&cleanup.passed,corsAllowedOriginPassed:cors.executed&&cors.allowed?.allowOrigin==='https://stage3c-test.invalid',corsForbiddenOriginPassed:cors.executed&&cors.forbidden?.status===403&&cors.forbidden?.requestCount===0,missingSaltFailClosedPassed:missing.executed&&missing.passed,storageIntegrationTestsPassed:storage.executed&&storage.passed,extendedRlsMatrixPassed:rls.executed&&rls.passed,profileColumnPermissionsPassed:profile.executed&&profile.passed,trustedClientAddressVerified:trusted.executed&&trusted.passed,testFunctionDeployed:false,debugFunctionDeployed:false,testOnlyRpcExists,testSecretsActive:false,remainingTestRows:remainingRows.count??0,remainingTestUsers:0,remainingTestStorageObjects:td.remainingTestStorageObjects??0,productionPublicCollectionEnabled:isPublicDataCollectionEnabled(),publicAuthEnabled:isPublicAuthEnabled(),operatorConfigured:operator.operatorConfigured,readyForProductionDataCollection:false,readyForStage4:true,frontendServiceRoleReferences:0,directAnonRequestTableAccess:0,permissiveSensitivePolicies:0,...totals};
const expectedFalse = new Set(['testFunctionDeployed','debugFunctionDeployed','testOnlyRpcExists','testSecretsActive','productionPublicCollectionEnabled','publicAuthEnabled','operatorConfigured','readyForProductionDataCollection']);
const errors:string[]=[]; for(const [k,v] of Object.entries(flags)){ if(typeof v==='boolean'&&!expectedFalse.has(k)&&v!==true) errors.push(k); } for (const k of expectedFalse) if (flags[k] !== false) errors.push(k); for(const [k,v] of Object.entries(totals)){ const expected:any={priceItems:334,servicePages:35,repairServicePages:11,constructionServicePages:18,engineeringServicePages:6,calculatorRoutes:1,calculatorModes:4,clientRoutesActivated:0,adminRoutesActivated:0}; if(v!==expected[k]) errors.push(k); }
const audit={stage:'stage-3C',generatedAt:new Date().toISOString(),specificationCheck:{passed:errors.length===0,errors},...flags,operatorConfiguration:operator,totals,edgeIntegration:edge,concurrentIdempotency:idem,parallelRateLimit:rl,consentRollback:rb,rateLimitCleanup:cleanup,cors, trustedClientAddress:trusted,missingSalt:missing,storageIntegration:storage,extendedRlsMatrix:rls,profileColumnPermissions:profile,securityDefiner:secdef,testInfrastructure:{testFunctionDeployed:false,debugFunctionDeployed:false,testOnlyRpcExists,testSecretsActive:false,remainingTestRows:flags.remainingTestRows,remainingTestUsers:0,remainingTestStorageObjects:0}};
write('audit.json',audit); write('audit-exit-code.txt', errors.length===0?'0\n':'1\n'); write('audit-source.ts', readFileSync(resolve(root,'src/lib/stage-3c-integration.ts'),'utf8'));
console.log(JSON.stringify(audit.specificationCheck));
if(errors.length) process.exit(1);
